/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.notes.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Note service. Represents a row in the &quot;NOTE_Note&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.notes.model.impl.NoteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.notes.model.impl.NoteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Note
 * @see com.liferay.notes.model.impl.NoteImpl
 * @see com.liferay.notes.model.impl.NoteModelImpl
 * @generated
 */
@ProviderType
public interface NoteModel extends BaseModel<Note>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a note model instance should use the {@link Note} interface instead.
	 */

	/**
	 * Returns the primary key of this note.
	 *
	 * @return the primary key of this note
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this note.
	 *
	 * @param primaryKey the primary key of this note
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this note.
	 *
	 * @return the uuid of this note
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this note.
	 *
	 * @param uuid the uuid of this note
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the note ID of this note.
	 *
	 * @return the note ID of this note
	 */
	public long getNoteId();

	/**
	 * Sets the note ID of this note.
	 *
	 * @param noteId the note ID of this note
	 */
	public void setNoteId(long noteId);

	/**
	 * Returns the group ID of this note.
	 *
	 * @return the group ID of this note
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this note.
	 *
	 * @param groupId the group ID of this note
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this note.
	 *
	 * @return the company ID of this note
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this note.
	 *
	 * @param companyId the company ID of this note
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this note.
	 *
	 * @return the user ID of this note
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this note.
	 *
	 * @param userId the user ID of this note
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this note.
	 *
	 * @return the user uuid of this note
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this note.
	 *
	 * @param userUuid the user uuid of this note
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this note.
	 *
	 * @return the user name of this note
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this note.
	 *
	 * @param userName the user name of this note
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this note.
	 *
	 * @return the create date of this note
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this note.
	 *
	 * @param createDate the create date of this note
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this note.
	 *
	 * @return the modified date of this note
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this note.
	 *
	 * @param modifiedDate the modified date of this note
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this note.
	 *
	 * @return the title of this note
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this note.
	 *
	 * @param title the title of this note
	 */
	public void setTitle(String title);

	/**
	 * Returns the posted of this note.
	 *
	 * @return the posted of this note
	 */
	public boolean getPosted();

	/**
	 * Returns <code>true</code> if this note is posted.
	 *
	 * @return <code>true</code> if this note is posted; <code>false</code> otherwise
	 */
	public boolean isPosted();

	/**
	 * Sets whether this note is posted.
	 *
	 * @param posted the posted of this note
	 */
	public void setPosted(boolean posted);

	/**
	 * Returns the items of this note.
	 *
	 * @return the items of this note
	 */
	public int getItems();

	/**
	 * Sets the items of this note.
	 *
	 * @param items the items of this note
	 */
	public void setItems(int items);

	/**
	 * Returns the content of this note.
	 *
	 * @return the content of this note
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this note.
	 *
	 * @param content the content of this note
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Note note);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Note> toCacheModel();

	@Override
	public Note toEscapedModel();

	@Override
	public Note toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}